##################################################
# Process the LT and Promotion files on RESB sever
# Ollie Le
# v1.0
##################################################

- name: "Process Files"
  win_shell: |
    $SourcePath = "{{destination_path}}"

    $CurrentDir = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
    $NextDir = Join-Path -Path $CurrentDir -ChildPath "..\scripts\process-promotion.ps1"
    & $NextDir -SourcePath $SourcePath